# Generated by Django 3.2.21 on 2023-10-02 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Concepto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_ult_mod', models.DateTimeField(auto_now=True, null=True)),
                ('fsn', models.CharField(max_length=255, verbose_name='Fully Specified Name')),
                ('dominio', models.IntegerField(choices=[(1, 'Imagenes'), (2, 'Procedimientos'), (3, 'Laboratorio')], default=1)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('usuario_creador', models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='mantenedor_concepto_related_crea', to=settings.AUTH_USER_MODEL)),
                ('usuario_ult_mod', models.ForeignKey(default=1, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mantenedor_concepto_related_modif', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'conceptos',
                'ordering': ['id'],
            },
        ),
    ]
